# config.yaml
apprise:
  summary: on_error
  urls:
    - 'discord://WebhookID/WebhookToken'  # Replace with your actual Apprise service URLs
attempts:
  base_delay_in_seconds: 14.0625 # base_delay_in_seconds * 2^max = 14.0625 * 2^6 = 900 = 15 minutes
  max: 8
  strategy: exponential
